#!/usr/bin/env bash
# It shows "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each repetition.
#   It shows "I am invincible!!!" in between each repetition.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
