#!/usr/bin/env bash
# It writes to a string indefinitely "I am alive" to the file /tmp/my_process.
#   it halts two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
