#!/usr/bin/env bash
# Server-01 login commands

# Start the SSH agent
eval "$(ssh-agent -s)"

# Add the SSH private key to the agent
ssh-add ~/.ssh/school

# Connect to the server 
ssh ubuntu@54.209.112.150
